### ISSUE TITLE
Setup fails on a clean Pi

### ISSUE THREAD

**Issue by chrisc-xmos** [xmos/vocalfusion_3510_avs_setup#16]
This setup process fails on a clean Pi with the error :
+1: make -C /lib/modules/`uname -r`/build M=/home/pi/vocalfusion_3510_avs_setup/vocalfusion-rpi-setup/i2c-gpio-param modules
make[1]: *** /lib/modules/4.14.79-v7+/build: No such file or directory.  Stop.
Makefile:6: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by DaveAtkinsonXMOS** [comment]
This repo is to be discontinued so I am closing this issue. Please reopen in the new unified xmos/vocalfusion-avs-setup repo if you have any futher issues. Thanks.
