### ISSUE TITLE
Latest update script doesn't set or mention environment variables

### ISSUE THREAD

**Issue by johned0** [xmos/vocalfusion_3510_avs_setup#26]
The following :
./auto_install.sh config.json
configures to use the environment variables (SDK_CONFIG_CLIENT_ID, SDK_CONFIG_CLIENT_SECRET andSDK_CONFIG_DEVICE_TYPE_ID) but doesn't set the values or document that they need to be set.
After setting the environment variables everythign worked fab.
J

**Comment by DaveAtkinsonXMOS** [comment]
This repo is to be discontinued so I am closing this issue. Please reopen in the new unified xmos/vocalfusion-avs-setup repo if you have any futher issues. Thanks.
