### ISSUE TITLE
./setup.sh: line 204: /home/pi/.config/lxsession/LXDE-pi/autostart: No such file or directory

### ISSUE THREAD

**Issue by oscarbailey-xmos** [xmos/vocalfusion_3510_avs_setup#3]
Automatically run AVS SDK at startup (y/n)? y
./setup.sh: line 204: /home/pi/.config/lxsession/LXDE-pi/autostart: No such file or directory

**Comment by DaveAtkinsonXMOS** [comment]
I believe this issue is closed. If not, please reopen in the new unified product setup in the vocalfusion-avs-setup repo.
