### ISSUE TITLE
Upgrade avs-device-sdk to Version 1.19.0 - current won't install

### ISSUE THREAD

**Issue by netkruzer** [xmos/vocalfusion_3510_avs_setup#36]
Tried installing on a fresh-ish raspberry pi image. Kept running into this error:

`libcurl4-openssl-dev : conflicts: libssl1.0-dev but 1.0.2q-2 is to be installed`

I found that changing the pi.sh file from installing `libssl1.0-dev` to just `libssl-dev` made the installation work.

I also found that the updated Alexa/avs-device-sdk file has that change made already.

https://github.com/alexa/avs-device-sdk/blob/master/tools/Install/pi.sh

I suggest updating your local copy for pi.sh on xmos/avs-device-sdk to the most recent Alexa/avs-device-sdk/tools/Install/pi.sh

This would fix that error.

**Comment by lucianomartin** [comment]
Hi @netkruzer, thanks for reporting this issue.

I merged the latest alexa/avs-device-sdk (v1.19) on top of the XMOS changes and I didn't manage to compile it, it freezes at 97% of the AVS compilation. I tried on both a RPi Model 3B and a Model 3B+ using kernel:

_Linux raspberrypi 4.19.66-v7+ #1253 SMP Thu Aug 15 11:49:46 BST 2019 armv7l GNU/Linux_

Can you let me know what kernel and hardware you used?

We cannot use more recent kernels at the moment as it causes a failure while building the I2S drivers.

Luciano

**Comment by netkruzer** [comment]
I gave up on the newest OS and switched back to Stretch:

```
cat /proc/device-tree/model
Raspberry Pi 3 Model B Rev 1.2

uname -a
Linux raspberrypi 4.19.66-v7+ #1253 SMP Thu Aug 15 11:49:46 BST 2019 armv7l GNU/Linux
```
I'm able to compile now, following the steps on this repo. I'm able to play audio out the 3.5mm jack on the daughter board, but I'm not able to record anything.

Any idea why Audacity would not record anything? I tried cycling through all of the recording inputs and nothing worked. I see the one multicolored light on the daughter board (on top of the Raspi) but nothing is lit on the microphone adapter board where the XMOS chip is.

I tried re-seating the cable, but still nothing. Any ideas?

**Comment by netkruzer** [comment]
Turns out, there is no documentation telling you the Raspberry Pi needs to be connected to the XMOS XVF3510 Motherboard through a Micro USB cable. The Motherboard is not powered by the Raspberry Pi backpack.
![image](https://user-images.githubusercontent.com/7841302/80621767-a0289700-89fc-11ea-86dc-79061b10fb69.png)
Raspberry Pi connection has 3v3.

![image](https://user-images.githubusercontent.com/7841302/80621813-b2a2d080-89fc-11ea-8133-8df6a2df371d.png)
XMOS motherboard does not have the 3v3 connected.

**Comment by netkruzer** [comment]
![image](https://user-images.githubusercontent.com/7841302/80628279-f8b06200-8a05-11ea-8706-ef76a8aa751c.png)
Connecting the 5v and GND to the USB connector powers and allows the XMOS board to transmit audio over the i2s connections. USB is not needed to get audio out of the XMOS motherboard.

**Comment by lucianomartin** [comment]
Hi @netkruzer, I am sorry about the issues you described in the previous comments. I am not 100% sure about the documentation included in the dev kit, but on the XMOS website we have this doc:
https://www.xmos.com/download/XVF3510-AVS-Quick-Start---PDF_IDD(August-2019).pdf
and at step 5 it mentions to connect the USB cable between the RPi and the XVF3510. As you correctly said, the XVF3510 is powered through that cable. It is not used for any USB communication in the AVS dev kit.
Let me know if you have any more questions or feedback, but it seems that everything is working as expected now.

**Comment by netkruzer** [comment]
Hi @lucianomartin, I did not see that document. I went off the github install guides and this document:  XVF3510-Quick-Start---PDF_IDD_2.pdf
![image](https://user-images.githubusercontent.com/7841302/80640920-f3104780-8a18-11ea-80f2-f94e09a4a00b.png)
It doesn't show the USB connected to the Raspberry Pi version of the board.

**Comment by netkruzer** [comment]
I guess it's my bad for not looking around more for more guidance. The one picture in the above does not have the USB connected to the Raspberry Pi. I would assume the Raspberry Pi Dev kit would connect and power fully over the ribbon cable, especially when it puts 3v on the ribbon, but the XMOS board has those pins disconnected.

**Comment by lucianomartin** [comment]
I see, the document you posted earlier is part of the non-AVS dev kit. It is our USB solution and it is not supposed to be used with the Raspberry Pi. Sorry for the confusion.
If you have any feedback about how to avoid this issue in the future, please let us know.

**Comment by DaveAtkinsonXMOS** [comment]
This repo is to be discontinued so I am closing this issue. Please reopen in the new unified xmos/vocalfusion-avs-setup repo if you have any futher issues. Thanks.
