### ISSUE TITLE
Readme error

### ISSUE THREAD

**Issue by chrisc-xmos** [xmos/vocalfusion_3510_avs_setup#6]
In the Readme, the link: http://github.com/alexa/alexa-avs-sample-app/wiki/Create-Security-Profile. is invalid

**Comment by DaveAtkinsonXMOS** [comment]
This repo is to be discontinued so I am closing this issue. I believe this is addressed in the new unified xmos/vocalfusion-avs-setup repo. Please reopen it there if you have any futher issues. Thanks.
