### ISSUE TITLE
Readme folder error

### ISSUE THREAD

**Issue by chrisc-xmos** [xmos/vocalfusion_3510_avs_setup#7]
In the Readme section "AVS SDK installation and Raspberry Pi audio setup" task 5 assumes that the used is in the vocalfusion_3510_avs_setup folder but the instructions don't say to cd into that folder

**Comment by DaveAtkinsonXMOS** [comment]
This repo is to be discontinued so I am closing this issue. I believe this has been addressed in the new unified xmos/vocalfusion-avs-setup repo, so please reopen it there if you have any futher issues. Thanks.
