### ISSUE TITLE
Readme error referencing other documents

### ISSUE THREAD

**Issue by chrisc-xmos** [xmos/vocalfusion_3510_avs_setup#8]
The readme references:

1. the hardware setup guide. This does not exist.
2. the Getting Started Guide. This does not describe any relevant steps for the setup of the AVS kit

**Comment by netkruzer** [comment]
FYI, I wish somewhere in the hardware setup would tell you that a USB cable from the RASBPERRY PI needs to be plugged into the XMOS board. The ribbon cable does not power the board. This took me far too long to realize.

**Comment by DaveAtkinsonXMOS** [comment]
This repo is to be discontinued so I am closing this issue. Please reopen in the new unified xmos/vocalfusion-avs-setup repo if you have any futher issues. Thanks.
